name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: autopoint 
      run: sudo sh -c 'locale-gen pl && apt-get install gettext autopoint'
    - name: autoreconf
      run: gettextize && autoreconf -fi
    - name: get-help
      run:  apt-cache show automake
    - name: configure
      run: sh -v configure
    - name: make
      run: make
    - name: Save the pot
      uses: actions/upload-artifact@v4.6.2
      with:
    # A file, directory or wildcard pattern that describes what to upload
        path: ./po/package.pot
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
    - name: Save the log
      if: always ()
      uses: actions/upload-artifact@v4.6.2
      with:
    # A file, directory or wildcard pattern that describes what to upload
        path: ./test-suite.log
